default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: any_progress_bars_development

test:
  <<: *default
  database: any_progress_bars_test

production:
  <<: *default
  database: any_progress_bars_production
  username: any_progress_bars
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
